os:
  - linux
language: java
jdk:
  - openjdk11
script:
  - set -e
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn clean install -Pcheckstyle,itcases # -PtestCoverage jacoco:report coveralls:report
